services:
  db:
    image: mysql:8.0.45
    container_name: mysql-container
    #ports:
    #  - "3307:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - ordini-pagamenti

  amq-broker:
    image: rabbitmq:3-management
    container_name: rabbit-mq-container
    hostname: my-rabbit
    #ports:
    #  - "5672:5672"
    #  - "15672:15672"
    networks:
      - ordini-pagamenti
    healthcheck:
      # "rabbitmq-diagnostics -q ping" è il comando ufficiale raccomandato
      # da RabbitMQ per verificare se il nodo è attivo e risponde.
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 3s
      timeout: 2s
      retries: 20

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml # Dice a Loki di usare la sua config standard interna
    networks:
      - ordini-pagamenti

  # Promtail prende dal volume i file di log e li passa a loki. Loki li registra internamente e Grafana usa
  # Loki per permettere il monitoraggio dei log.
  # Essenzialmente Promtail si occupa solo da fare da ponte tra i log presenti nel volume e loki
  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      # Mettiamo ":ro" (Read Only) perché Promtail deve solo LEGGERE, non cancellare o scrivere log
      - loki_logs_volume:/var/log/apps:ro

      # Usiamo un binding mount per usare le configurazioni locali nel container
      - ./promtail:/etc/promtail
    networks:
      - ordini-pagamenti
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4567:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - ordini-pagamenti
    volumes:
      - grafana_volume:/var/lib/grafana # Serve a Grafana per ricordarsi i grafici che crei se lo spegni
    depends_on:
      - loki

  gateway:
    build: ./gateway
    image: homelesschicken/ordini-e-pagamenti-gateway:0.0.3
    container_name: ordini-pagamenti-gateway-container
    ports:
      - "8080:8080"
    environment:
      - GESTIONE_ORDINI_HOST=gestione-ordini-container
      - PATH_ORDINI=api/ordini
      - GESTIONE_PAGAMENTI_HOST=gestione-pagamenti-container
      - PATH_PAGAMENTI=api/pagamenti
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AUTH_HOST=ordini-pagamenti-auth-container
      - AUTH_PORT=8080
      - PATH_AUTH=api/auth
    networks:
      - ordini-pagamenti
    depends_on:
      ordini:
        # Con questo diciamo a docker: avvia questo container SOLO dopo che sei sicuro che il container del servizio
        # degli ordini sia "healthy" ovvero, nel nostro caso, dopo che il comando curl sia andato a buon fine.
        # Se non lo mettessimo diremo a docker di avviare il gateway un istante (letteralmente pochissimi milllisecondi)
        # dopo aver avviato gli ordini, fregandosene dell'esito.
        condition: service_healthy
      pagamenti:
        condition: service_healthy
      auth:
        condition: service_healthy

  auth:
    build: ./auth
    image: homelesschicken/ordini-e-pagamenti-auth:0.0.2
    container_name: ordini-pagamenti-auth-container
    #ports:
    #  - "8083:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-container:3306/ordini_e_pagamenti_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_MILLIS=300000
    networks:
      - ordini-pagamenti
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/auth/health"]
      interval: 1500ms
      timeout: 1s
      retries: 10

  ordini:
    build: ./ordini
    image: homelesschicken/gestione-ordini:0.0.5
    container_name: gestione-ordini-container
    #ports:
    #  - "8081:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-container:3306/gestione_ordini
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PAGAMENTO_URL=http://gestione-pagamenti-container:8080/api
      - AUTH_URL=http://ordini-pagamenti-auth-container:8080/api/internal/auth
      - RABBITMQ_HOST=rabbit-mq-container
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - REPORTS_TEMPLATE_DIR=/app/reports/template/
      - REPORTS_TEMPLATE_FILENAME=order-payment-receipt
      - BUCKET_S3_NAME=its-s3-demo-551656632325-eu-south-1-an
      - BUCKET_ROOT_PREFIX=c.coccia
      - AWS_ACCESS_KEY_ID_FILE=/run/secrets/aws_access_key_id # Dice dove si trova all'interno del container il file con le credenziali
      - AWS_SECRET_ACCESS_KEY_FILE=/run/secrets/aws_secret_access_key # Dice dove si trova all'interno del container il file con le credenziali
      - AWS_REGION=eu-south-1
      #- LOG_ROOT_LEVEL=DEBUG
    # Passa i segreti di docker (i file definiti sotto) al servizio ordini. Docker creerà all'interno del container
    # una cartella chiamata /run/secrets/ dove ci sono questi due file.
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    networks:
      - ordini-pagamenti
    depends_on:
      db:
        condition: service_started
      amq-broker:
          condition: service_healthy
    volumes:
      - loki_logs_volume:/app/logs
      - ./ordini/ricevute:/app/ricevute
    # Healthcheck: quando il container viene tirato su, esegui questo comando all'interno del container stesso, per vedere
    # che stia funzionando correttamente.
    # NOTARE: Siccome siamo all'interno del container, possiamo usare la sua porta interna (8080) e non c'è bisogno
    # ne di usare il DNS di docker ne di usare la porta mappata sul pc.
    healthcheck:
      # Usa curl. Curl è un programma da terminale per fare chiamate http, come postman. Il -f significa "dammi un errore
      # se mi ritorna uno status code diverso da 2XX. In questo modo docker vede l'errore e capisce che è andato male il tentativo
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/ordini/health"]
      # Esegui un tentativo (un comando) ogni 10 secondi
      interval: 1500ms
      # Il tentativo corrente è andato male se ci mette più di 5 secondi (per esempio il microservizio è spento e dunque non risponde)
      timeout: 1s
      # Massimo 5 tentativi. Dopodichè accettiamo che il container non sia "in salute"
      retries: 10

  pagamenti:
    build: ./pagamenti
    image: homelesschicken/gestione-pagamenti:0.0.3
    container_name: gestione-pagamenti-container
    #ports:
    #  - "8082:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-container:3306/gestione_ordini
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ_HOST=rabbit-mq-container
    networks:
      - ordini-pagamenti
    depends_on:
      db:
        condition: service_started
      amq-broker:
        condition: service_healthy
      ordini:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/pagamenti/health"]
      interval: 1500ms
      timeout: 1s
      retries: 10

networks:
  ordini-pagamenti:

volumes:
  mysql_volume:
    external: true
    name: mysql_volume
  loki_logs_volume:
  grafana_volume:

# Configura i segreti: prendi dalla macchina host questi file e mettili come "segreti" che i servizi possono usare
secrets:
  aws_access_key_id:
      file: ./secrets/access_key_id.txt
  aws_secret_access_key:
      file: ./secrets/access_key_secret.txt